config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :offices
  resources :tasks
  resources :projects do
    collection do
      post 'assign_project'
    end
    member do
      post 'assign_task'
    end
  end

  resources :user_tasks
  resources :project_users

  # root to: "prjects#assign_task"
  # get '/submit' to: '[ro]s#new'
end



# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

app/models/office.rb
class Office < ApplicationRecord
  has_many :users
  has_many :projects
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController

  def index
    @offices = Office.all
  end

  def new
    @office=Office.new
  end

  def show
    @office = Office.find(params[:id])
    @projects =  @office.projects
  end


  def create
    @office = Office.new(project_params)
    if @office.save
      redirect_to project_path(@office)
    else
      flash[:success] = "record created"
      render :action => 'new'
    end
  end

  def login
  end

  # def office_projects
  # @office = Office.project
  # end

  private

  def project_params
    params.require(:project).permit(:oname)
  end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/index.html.erb
<div class="main-content">
  <nav class="navbar navbar-top navbar-expand-md navbar-dark" id="navbar-main">
    <div class="container-fluid">
      <a class="h4 mb-0 text-white text-uppercase d-none d-lg-inline-block" href="../index.html">Tables</a>
    </div>
  </nav>
  <br>
  <br>
  <div class="container-fluid mt-7">
    <div class="row">
      <div class="col">
        <div class="card bg-default shadow">
          <div class="card-header bg-transparent border-0">
            <h3 class="text-white mb-0">Card tables</h3>
            <%= link_to '<button type="button">Show</button>'.html_safe, projects_path %>
          </div>
          <div class="table-responsive">
            <table class="table align-items-center table-dark table-flush">
              <thead class="thead-dark">
                <tr>
                  <th scope="col">Office name </th>
                  <th scope="col">Office Project</th>
                </tr>
              </thead>
              <tbody>
                <% @offices.each do |office| %>
                <tr>
                  <th>
                    <span class="mb-0 text-sm">
                      <%= office.oname %>
                    </span>
                    <td>
                      <%= link_to '<button type="button">Project</button>'.html_safe, office_path(office.id)  %>
                    </td>
                  </tr>
                  <% end %>
              </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
        <footer class="footer">
          <div class="row align-items-center justify-content-xl-between">
            <div class="col-xl-6">
              <div class="copyright text-center text-xl-left text-muted">
                &copy; 2018 <a href="https://www.creative-tim.com" class="font-weight-bold ml-1" target="_blank">Creative Tim</a>
              </div>
            </div>
            <div class="col-xl-6">
              <ul class="nav nav-footer justify-content-center justify-content-xl-end">
                <li class="nav-item">
                  <a href="https://www.creative-tim.com" class="nav-link" target="_blank">Creative Tim</a>
                </li>
                <li class="nav-item">
                  <a href="https://www.creative-tim.com/presentation" class="nav-link" target="_blank">About Us</a>
                </li>
                <li class="nav-item">
                  <a href="http://blog.creative-tim.com" class="nav-link" target="_blank">Blog</a>
                </li>
                <li class="nav-item">
                  <a href="https://github.com/creativetimofficial/argon-dashboard/blob/master/LICENSE.md" class="nav-link" target="_blank">MIT License</a>
                </li>
              </ul>
            </div>
          </div>
        </footer>
      </div>
    </div>




    <td><%#= project.office.try(:id) %></td>

app/views/offices/login.html.erb
<h1>dsjkvhjkfhvjkfhjk</h1>

app/views/offices/show.html.erb
<div class="content">
  <div class="row">
    <div class="col-8 offset-2">
      <table class="reports">
        <tr>
          <td>
            <%= @office.oname %>
          </td>
        </tr>
      </table>
        <% @projects.each do |project| %>
        <div class="row">
          <tr>
            <td>
              <%= project.pname %>
            </td>
          </tr>
        </div>
        <% end %>
    </div>
  </div>

</div>